version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset_dm017:
    run: >
      databuilder:v0 
        generate-dataset analysis/dataset_definition_dm_reg.py
        --dummy-tables dummy_data
        --output output/dataset_dm_reg.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_dm_reg.csv
