version: '3.0'

expectations:
  population_size: 100

actions:

# Generate datasets
## DM017
  generate_dataset_dm017:
    run: >
      ehrql:v0 
        generate-measures analysis/dataset_definition_dm017.py
        --dummy-tables dummy_data
        --output output/measures/dataset_dm017.csv
    outputs:
      moderately_sensitive:
        cohort: output/measures/dataset_dm017.csv

## DM020
  generate_dataset_dm020:
    run: >
      ehrql:v0 
        generate-measures analysis/dataset_definition_dm020.py
        --dummy-tables dummy_data
        --output output/measures/dataset_dm020.csv
        -- 
        --ifcchba-cutoff-val "58"
    outputs:
      moderately_sensitive:
        cohort: output/measures/dataset_dm020.csv


## DM021
  generate_dataset_dm021:
    run: >
      ehrql:v0 
        generate-measures analysis/dataset_definition_dm021.py
        --dummy-tables dummy_data
        --output output/measures/dataset_dm021.csv
        -- 
        --ifcchba-cutoff-val "75"
    outputs:
      moderately_sensitive:
        cohort: output/measures/dataset_dm021.csv

