version: '3.0'

expectations:
  population_size: 100

actions:

# Generate datasets
## DM017
  test_dm017:
    run: >
      ehrql:v0 
        generate-dataset analysis/dataset_definition_dm017.py
        --dummy-tables dummy_data
        --output output/datasets/dataset_dm017.csv
    outputs:
      moderately_sensitive:
        cohort: output/datasets/dataset_dm017.csv

  generate_measures_dm017:
    run: >
      ehrql:v0 
        generate-measures analysis/dataset_definition_dm017.py
        --dummy-tables dummy_data
        --output output/measures/measures_dm017.csv
    outputs:
      moderately_sensitive:
        cohort: output/measures/measures_dm017.csv


## DM020
  test_dm020:
    run: >
      ehrql:v0 
        generate-dataset analysis/dataset_definition_dm020.py
        --dummy-tables dummy_data
        --output output/datasets/dataset_dm020.csv
        -- 
        --ifcchba-cutoff-val "58"
    outputs:
      moderately_sensitive:
        cohort: output/datasets/dataset_dm020.csv
  
  generate_measures_dm020:
    run: >
      ehrql:v0 
        generate-measures analysis/dataset_definition_dm020.py
        --dummy-tables dummy_data
        --output output/measures/measures_dm020.csv
        -- 
        --ifcchba-cutoff-val "58"
    outputs:
      moderately_sensitive:
        cohort: output/measures/measures_dm020.csv


## DM021
  test_dm021:
    run: >
      ehrql:v0 
        generate-dataset analysis/dataset_definition_dm021.py
        --dummy-tables dummy_data
        --output output/datasets/dataset_dm021.csv
        -- 
        --ifcchba-cutoff-val "75"
    outputs:
      moderately_sensitive:
        cohort: output/datasets/dataset_dm021.csv
  
  generate_measures_dm021:
    run: >
      ehrql:v0 
        generate-measures analysis/dataset_definition_dm021.py
        --dummy-tables dummy_data
        --output output/measures/measures_dm021.csv
        -- 
        --ifcchba-cutoff-val "75"
    outputs:
      moderately_sensitive:
        cohort: output/measures/measures_dm021.csv

