version: '3.0'

expectations:
  population_size: 100

actions:

  generate_dataset_dm017_2022-03-01:
    run: >
      ehrql:v0 
        generate-dataset analysis/dataset_definition_dm017.py
        --dummy-tables dummy_data
        --output output/datasets/dm017_dataset_2022-03-01.csv
        -- 2022-03-01 2022-03-31
    outputs:
      highly_sensitive:
        cohort: output/datasets/dm017_dataset_2022-03-01.csv

  generate_measures_dm017:
    run: >
      ehrql:v0 
        generate-measures analysis/dataset_definition_dm017.py
        --dummy-tables dummy_data
        --output output/measures/dm017_measures.csv
    outputs:
      moderately_sensitive:
        cohort: output/measures/dm017_measures.csv
  
  generate_measures_dm020:
    run: >
      ehrql:v0 
        generate-measures analysis/dataset_definition_dm020.py
        --dummy-tables dummy_data
        --output output/measures/dm020_measures.csv
        -- 
        --ifcchba-cutoff-val 58
    outputs:
      moderately_sensitive:
        cohort: output/measures/dm020_measures.csv
  
  generate_measures_dm021:
    run: >
      ehrql:v0 
        generate-measures analysis/dataset_definition_dm021.py
        --dummy-tables dummy_data
        --output output/measures/dm021_measures.csv
        -- 
        --ifcchba-cutoff-val 75
    outputs:
      moderately_sensitive:
        cohort: output/measures/dm021_measures.csv
