version: '3.0'

expectations:
  population_size: 100

actions:

  generate_measures_dm017:
    run: >
      ehrql:v1 
        generate-measures analysis/dataset_definition_dm017.py
        --dummy-tables dummy_data
        --output output/measures/measures_dm017.csv
    outputs:
      moderately_sensitive:
        cohort: output/measures/measures_dm017.csv
  
  generate_measures_dm020:
    run: >
      ehrql:v1 
        generate-measures analysis/dataset_definition_dm020.py
        --dummy-tables dummy_data
        --output output/measures/measures_dm020.csv
        -- 
        --ifcchba-cutoff-val 58
    outputs:
      moderately_sensitive:
        cohort: output/measures/measures_dm020.csv
  
  generate_measures_dm021:
    run: >
      ehrql:v1 
        generate-measures analysis/dataset_definition_dm021.py
        --dummy-tables dummy_data
        --output output/measures/measures_dm021.csv
        -- 
        --ifcchba-cutoff-val 75
    outputs:
      moderately_sensitive:
        cohort: output/measures/measures_dm021.csv
